// user-app/doc/安诊达原型文件/src/pages/Orders.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import {
  FileText,
  Star,
  MapPin,
  Clock,
  ChevronRight,
  MessageSquare,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import {
  FadeIn,
  Stagger,
  HoverLift,
  fadeUp,
  motion,
} from "@/components/MotionPrimitives";
import { orders } from "@/data/mockData";

type TabType = "in_progress" | "completed" | "cancelled";

const tabs: { key: TabType; label: string }[] = [
  { key: "in_progress", label: "进行中" },
  { key: "completed", label: "已完成" },
  { key: "cancelled", label: "已取消" },
];

const statusConfig: Record<
  string,
  { label: string; bg: string; color: string }
> = {
  pending: { label: "待确认", bg: "#FFF5E0", color: "#F5A623" },
  accepted: { label: "已接单", bg: "#EBF3FC", color: "#4A90D9" },
  in_progress: { label: "进行中", bg: "#E8F5EE", color: "#2B9A6F" },
  completed: { label: "已完成", bg: "#EBF3FC", color: "#4A90D9" },
  cancelled: { label: "已取消", bg: "#F3F0EB", color: "#9CA3AF" },
};

function RatingSheet({
  open,
  onOpenChange,
  orderId: _orderId,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  orderId: string;
}) {
  const [rating, setRating] = useState(0);
  const [review, setReview] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    setSubmitted(true);
    setTimeout(() => {
      onOpenChange(false);
      setSubmitted(false);
      setRating(0);
      setReview("");
    }, 1500);
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="bottom" className="rounded-t-3xl px-6 pb-10">
        <SheetHeader className="mb-6">
          <SheetTitle
            className="text-center font-bold"
            style={{ fontSize: 20, color: "#2D2D2D" }}
          >
            服务评价
          </SheetTitle>
        </SheetHeader>

        {submitted ? (
          <div className="flex flex-col items-center py-8">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: "spring", damping: 12, stiffness: 200 }}
              className="w-16 h-16 rounded-full flex items-center justify-center mb-4"
              style={{ background: "#E8F5EE" }}
            >
              <MessageSquare className="w-7 h-7" style={{ color: "#2B9A6F" }} />
            </motion.div>
            <span
              className="font-semibold"
              style={{ fontSize: 18, color: "#2D2D2D" }}
            >
              感谢您的评价
            </span>
          </div>
        ) : (
          <>
            {/* Star rating */}
            <div className="flex justify-center gap-3 mb-6">
              {[1, 2, 3, 4, 5].map((star) => (
                <button
                  key={star}
                  onClick={() => setRating(star)}
                  className="p-1"
                  style={{ minWidth: 44, minHeight: 44 }}
                >
                  <Star
                    className="w-9 h-9 transition-colors"
                    fill={star <= rating ? "#F5A623" : "transparent"}
                    style={{
                      color: star <= rating ? "#F5A623" : "#E8E5E0",
                    }}
                  />
                </button>
              ))}
            </div>

            {/* Review text */}
            <textarea
              value={review}
              onChange={(e) => setReview(e.target.value)}
              placeholder="分享您的服务体验（选填）"
              className="w-full p-4 border-0 resize-none focus:outline-none focus:ring-2 focus:ring-[#2B9A6F]/30"
              style={{
                background: "#F3F0EB",
                borderRadius: 16,
                fontSize: 16,
                color: "#2D2D2D",
                minHeight: 120,
              }}
            />

            {/* Submit */}
            <Button
              onClick={handleSubmit}
              disabled={rating === 0}
              className="w-full mt-5 border-0 font-semibold text-white disabled:opacity-50"
              style={{
                height: 56,
                borderRadius: 16,
                fontSize: 18,
                background:
                  rating > 0
                    ? "linear-gradient(135deg, #2B9A6F 0%, #3DB88A 100%)"
                    : "#E8E5E0",
              }}
            >
              提交评价
            </Button>
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}

function OrderCard({ order }: { order: (typeof orders)[0] }) {
  const [ratingOpen, setRatingOpen] = useState(false);
  const status = statusConfig[order.status] || statusConfig.pending;

  return (
    <>
      <HoverLift>
        <Card
          className="border-0 p-5"
          style={{
            borderRadius: 20,
            boxShadow:
              "0 2px 12px rgba(45, 45, 45, 0.06), 0 1px 4px rgba(45, 45, 45, 0.04)",
          }}
        >
          {/* Header: Order ID + Status */}
          <div className="flex items-center justify-between mb-3">
            <span style={{ fontSize: 16, color: "#9CA3AF" }}>{order.id}</span>
            <Badge
              className="border-0 font-medium"
              style={{
                background: status.bg,
                color: status.color,
                borderRadius: 20,
fontSize: 15,
                    padding: "4px 12px",
              }}
            >
              {status.label}
            </Badge>
          </div>

          {/* Service info */}
          <div className="mb-3">
            <h3
              className="font-bold"
              style={{ fontSize: 18, color: "#2D2D2D" }}
            >
              {order.serviceType}
            </h3>
            <div className="flex items-center gap-1.5 mt-1.5">
              <MapPin
                className="w-4 h-4 shrink-0"
                style={{ color: "#9CA3AF" }}
              />
              <span style={{ fontSize: 18, color: "#6B7280" }}>
                {order.hospital}
              </span>
            </div>
            <div className="flex items-center gap-1.5 mt-1">
              <Clock
                className="w-4 h-4 shrink-0"
                style={{ color: "#9CA3AF" }}
              />
              <span style={{ fontSize: 18, color: "#6B7280" }}>
                {order.date} {order.time}
              </span>
            </div>
          </div>

          {/* Companion info */}
          <div
            className="flex items-center gap-3 p-3 mb-3"
            style={{ background: "#F3F0EB", borderRadius: 14 }}
          >
            <div
              className="w-10 h-10 rounded-full flex items-center justify-center shrink-0"
              style={{
                background:
                  "linear-gradient(135deg, #E8F5EE 0%, #D4EDE2 100%)",
              }}
            >
              <span className="text-base font-bold" style={{ color: "#2B9A6F" }}>
                {order.companionName.charAt(0)}
              </span>
            </div>
            <div className="grow">
              <span
                className="font-semibold"
                style={{ fontSize: 18, color: "#2D2D2D" }}
              >
                {order.companionName}
              </span>
            </div>
            <div className="flex items-center gap-0.5">
              <Star
                className="w-3.5 h-3.5"
                fill="#F5A623"
                style={{ color: "#F5A623" }}
              />
              <span
                className="font-medium"
                style={{ fontSize: 16, color: "#2D2D2D" }}
              >
                {
                  // Find companion rating from companions data if available
                  order.rating || "4.9"
                }
              </span>
            </div>
          </div>

          {/* Review excerpt (if completed with review) */}
          {order.status === "completed" && order.review && (
            <div
              className="p-3 mb-3"
              style={{ background: "#FFF9F0", borderRadius: 14 }}
            >
              <div className="flex items-center gap-1 mb-1">
                {Array.from({ length: order.rating || 0 }).map((_, i) => (
                  <Star
                    key={i}
                    className="w-3.5 h-3.5"
                    fill="#F5A623"
                    style={{ color: "#F5A623" }}
                  />
                ))}
              </div>
              <p
                className="line-clamp-2"
                style={{ fontSize: 16, color: "#6B7280", lineHeight: 1.5 }}
              >
                {order.review}
              </p>
            </div>
          )}

          {/* Bottom: Fee + Action */}
          <div className="flex items-center justify-between pt-2">
            <div>
              <span style={{ fontSize: 16, color: "#9CA3AF" }}>合计 </span>
              <span
                className="font-bold"
                style={{ fontSize: 22, color: "#2B9A6F" }}
              >
                ¥{order.totalFee}
              </span>
            </div>

            {order.status === "in_progress" && (
              <Link to="/tracking">
                <Button
                  className="border-0 font-semibold text-white"
                  style={{
                    height: 44,
                    borderRadius: 14,
                    background:
                      "linear-gradient(135deg, #2B9A6F 0%, #3DB88A 100%)",
                    fontSize: 18,
                    padding: "0 20px",
                  }}
                >
                  查看进度
                  <ChevronRight className="w-4 h-4 ml-1" />
                </Button>
              </Link>
            )}

            {order.status === "completed" && !order.review && (
              <Button
                onClick={() => setRatingOpen(true)}
                variant="outline"
                className="font-semibold"
                style={{
                  height: 44,
                  borderRadius: 14,
                  borderColor: "#2B9A6F",
                  color: "#2B9A6F",
                  fontSize: 18,
                  padding: "0 20px",
                }}
              >
                <MessageSquare className="w-4 h-4 mr-1.5" />
                去评价
              </Button>
            )}
          </div>
        </Card>
      </HoverLift>

      <RatingSheet
        open={ratingOpen}
        onOpenChange={setRatingOpen}
        orderId={order.id}
      />
    </>
  );
}

export default function Orders() {
  const [activeTab, setActiveTab] = useState<TabType>("in_progress");

  const filteredOrders = orders.filter((order) => {
    if (activeTab === "in_progress") {
      return (
        order.status === "in_progress" ||
        order.status === "pending" ||
        order.status === "accepted"
      );
    }
    return order.status === activeTab;
  });

  return (
    <div className="min-h-screen pb-24" style={{ background: "#FAFAF8" }}>
      {/* Page Header */}
      <FadeIn>
        <div className="px-5 pt-6 pb-2">
          <h1
            className="font-bold"
            style={{ fontSize: 24, color: "#2D2D2D" }}
          >
            我的订单
          </h1>
          <p className="mt-1" style={{ fontSize: 18, color: "#9CA3AF" }}>
            共 {orders.length} 个订单
          </p>
        </div>
      </FadeIn>

      {/* Tab Filters */}
      <FadeIn delay={0.05}>
        <div className="px-5 py-3">
          <div className="flex gap-3">
            {tabs.map((tab) => {
              const isActive = activeTab === tab.key;
              const count = orders.filter((o) => {
                if (tab.key === "in_progress") {
                  return (
                    o.status === "in_progress" ||
                    o.status === "pending" ||
                    o.status === "accepted"
                  );
                }
                return o.status === tab.key;
              }).length;

              return (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className="flex items-center gap-1.5 px-5 font-semibold transition-all"
                  style={{
                    height: 44,
                    borderRadius: 22,
                    fontSize: 18,
                    background: isActive ? "#2B9A6F" : "#F3F0EB",
                    color: isActive ? "#FFFFFF" : "#6B7280",
                    minWidth: 80,
                    boxShadow: isActive
                      ? "0 4px 12px rgba(43, 154, 111, 0.25)"
                      : "none",
                  }}
                >
                  {tab.label}
                  {count > 0 && (
                    <span
                      className="text-xs font-bold px-1.5 py-0.5 rounded-full"
                      style={{
                        background: isActive
                          ? "rgba(255,255,255,0.25)"
                          : "rgba(0,0,0,0.06)",
                        fontSize: 14,
                      }}
                    >
                      {count}
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      </FadeIn>

      {/* Order List */}
      <Stagger stagger={0.08} className="px-5 space-y-4">
        {filteredOrders.length > 0 ? (
          filteredOrders.map((order) => (
            <motion.div key={order.id} variants={fadeUp}>
              <OrderCard order={order} />
            </motion.div>
          ))
        ) : (
          <motion.div variants={fadeUp}>
            <div
              className="flex flex-col items-center py-16"
              style={{ color: "#9CA3AF" }}
            >
              <FileText className="w-12 h-12 mb-3 opacity-40" />
              <span style={{ fontSize: 18 }}>暂无{tabs.find((t) => t.key === activeTab)?.label}订单</span>
            </div>
          </motion.div>
        )}
      </Stagger>
    </div>
  );
}

// user-app/pages/orders/index.vue
<template>
	<AzShell active="orders">
		<view class="page">
			<view class="header">
				<text class="title">我的订单</text>
				<text class="sub">共 {{ orders.length }} 个订单</text>
				<text class="refresh-tip">下拉页面可刷新订单状态</text>
			</view>

			<view class="current-card">
				<text class="current-label">当前服务对象</text>
				<text class="current-name">
					{{ currentPatient ? `${currentPatient.name}（${currentPatient.remarkRelation}）` : '暂未设置' }}
				</text>
				<text class="current-desc">订单列表会优先展示与当前就诊人相关的订单</text>
			</view>

			<view class="tabs">
				<view
					v-for="tab in tabs"
					:key="tab.key"
					class="tab"
					:class="{ active: activeTab === tab.key }"
					@tap="activeTab = tab.key"
				>
					<text>{{ tab.label }}</text>
					<text v-if="tabCount(tab.key) > 0" class="count">{{ tabCount(tab.key) }}</text>
				</view>
			</view>

			<view class="list">
				<view v-if="filteredOrders.length === 0" class="empty">
					<AzIcon name="file" :size="48" color="#D1D5DB" />
					<text>暂无{{ currentTabLabel }}订单</text>
				</view>

				<view v-for="order in filteredOrders" :key="order.id" class="order-card">
					<view class="row between">
						<text class="order-id">{{ order.orderNo || order.id }}</text>
						<text
							class="badge"
							:style="{
								background: getStageConfig(order).bg,
								color: getStageConfig(order).color
							}"
						>
							{{ getStageConfig(order).label }}
						</text>
					</view>

					<view class="patient-banner" :class="{ current: currentPatient && currentPatient.id === order.patientId }">
						<text class="patient-text">服务对象：{{ order.patientName }}（{{ order.patientRelation }}）</text>
					</view>

					<text class="service-name">{{ order.serviceType }}</text>
					<view class="info-line">
						<AzIcon name="location" :size="16" color="#9CA3AF" />
						<text>{{ order.hospital }}</text>
					</view>
					<view class="info-line">
						<AzIcon name="clock" :size="16" color="#9CA3AF" />
						<text>{{ order.date }} {{ order.time }}</text>
					</view>

					<view class="progress-box">
						<text class="progress-title">{{ getOrderProgressText(order) }}</text>
						<text v-if="order.pickupProofImage" class="progress-proof">陪诊员已上传接到用户核验图片</text>
					</view>

					<view class="companion">
						<view class="avatar">{{ getCompanionName(order).charAt(0) }}</view>
						<view class="companion-main">
							<text class="companion-name">{{ getCompanionName(order) }}</text>
							<text class="companion-stage">{{ getStageConfig(order).label }}</text>
						</view>
						<view class="score">
							<AzIcon name="star" :size="14" color="#F5A623" />
							<text>{{ order.rating || order.companionRating || '4.9' }}</text>
						</view>
					</view>

					<view v-if="order.status === 'completed' && order.review" class="review-box">
						<view class="small-stars">
							<AzIcon v-for="n in order.rating" :key="n" name="star" :size="14" color="#F5A623" />
						</view>
						<text>{{ order.review }}</text>
					</view>

					<view class="row between footer">
						<view>
							<text class="total-label">合计 </text>
							<text class="total">¥{{ order.totalFee }}</text>
						</view>
						<view v-if="order.canPay" class="outline" @tap="goPay(order)">去支付</view>
						<view v-else-if="order.status === 'completed' && !order.review" class="outline" @tap="openRating(order.id)">去评价</view>
						<view v-else class="primary" @tap="goTracking(order)">
							查看进度
							<AzIcon name="right" :size="16" color="#FFFFFF" />
						</view>
					</view>
				</view>
			</view>

			<view v-if="ratingOpen" class="sheet-mask" @tap="closeRating">
				<view class="sheet" @tap.stop>
					<view class="sheet-handle" />
					<text class="sheet-title">服务评价</text>
					<view v-if="submitted" class="thanks">
						<view class="thanks-icon"><AzIcon name="message" :size="28" color="#2B9A6F" /></view>
						<text>感谢您的评价</text>
					</view>
					<view v-else>
						<view class="rating-row">
							<AzIcon
								v-for="n in 5"
								:key="n"
								name="star"
								:size="36"
								:color="n <= rating ? '#F5A623' : '#E8E5E0'"
								@tap="rating = n"
							/>
						</view>
						<textarea v-model="review" class="textarea" placeholder="分享您的服务体验（选填）" />
						<view class="submit" :class="{ disabled: rating === 0 }" @tap="submitRating">提交评价</view>
					</view>
				</view>
			</view>
		</view>
	</AzShell>
</template>

<script>
import AzShell from '@/components/AzShell.vue'
import AzIcon from '@/components/AzIcon.vue'
import { getCurrentPatient, initFamilyCareStore, setCurrentPatient } from '@/utils/family-care.js'
import {
	getOrderCompanionName,
	getOrderProgressText,
	getOrderStage,
	getOrderStageLabel,
	listOrders,
	reviewOrder
} from '@/utils/order-service.js'

export default {
	components: { AzShell, AzIcon },
	data() {
		return {
			orders: [],
			activeTab: 'in_progress',
			ratingOpen: false,
			rating: 0,
			review: '',
			submitted: false,
			activeOrderId: '',
			tabs: [
				{ key: 'in_progress', label: '进行中' },
				{ key: 'completed', label: '已完成' },
				{ key: 'cancelled', label: '已取消' }
			],
			stageConfig: {
				pending_payment: { bg: '#FFF5E0', color: '#F5A623' },
				waiting_accept: { bg: '#FFF5E0', color: '#D88422' },
				accepted: { bg: '#EBF3FC', color: '#4A90D9' },
				on_the_way: { bg: '#E8F5EE', color: '#2B9A6F' },
				picked_up: { bg: '#E8F5EE', color: '#2B9A6F' },
				arrived: { bg: '#E8F5EE', color: '#2B9A6F' },
				serving: { bg: '#E8F5EE', color: '#2B9A6F' },
				completed: { bg: '#EBF3FC', color: '#4A90D9' },
				cancelled: { bg: '#F3F0EB', color: '#9CA3AF' }
			}
		}
	},
	computed: {
		currentPatient() {
			return getCurrentPatient()
		},
		filteredOrders() {
			const currentId = this.currentPatient?.id
			return this.orders
				.filter(order => this.inTab(order, this.activeTab))
				.sort((a, b) => {
					const aWeight = currentId && a.patientId === currentId ? 1 : 0
					const bWeight = currentId && b.patientId === currentId ? 1 : 0
					return bWeight - aWeight
				})
		},
		currentTabLabel() {
			return this.tabs.find(item => item.key === this.activeTab)?.label || ''
		}
	},
	created() {
		initFamilyCareStore()
	},
	onShow() {
		this.loadOrders()
	},
	onPullDownRefresh() {
		this.loadOrders().finally(() => {
			uni.stopPullDownRefresh()
		})
	},
	methods: {
		async loadOrders() {
			try {
				this.orders = await listOrders()
			} catch (error) {
				uni.showToast({
					title: error.message || '获取订单失败',
					icon: 'none'
				})
			}
		},
		inTab(order, key) {
			if (key === 'in_progress') {
				return !['completed', 'cancelled'].includes(order.status)
			}
			return order.status === key
		},
		tabCount(key) {
			return this.orders.filter(order => this.inTab(order, key)).length
		},
		getStageConfig(order) {
			const stage = getOrderStage(order)
			return {
				label: getOrderStageLabel(order),
				...(this.stageConfig[stage] || { bg: '#F3F0EB', color: '#9CA3AF' })
			}
		},
		getCompanionName(order) {
			return getOrderCompanionName(order)
		},
		getOrderProgressText,
		goTracking(order) {
			uni.navigateTo({ url: `/pages/tracking/index?orderId=${order.id}` })
		},
		goPay(order) {
			setCurrentPatient(order.patientId)
			const query = [
				`patientId=${order.patientId}`,
				`orderId=${order.id}`
			].join('&')
			uni.navigateTo({ url: `/pages/payment/index?${query}` })
		},
		openRating(orderId) {
			this.activeOrderId = orderId
			this.ratingOpen = true
			this.rating = 0
			this.review = ''
			this.submitted = false
		},
		closeRating() {
			this.ratingOpen = false
			this.submitted = false
			this.activeOrderId = ''
		},
		async submitRating() {
			if (!this.rating) return
			try {
				const updatedOrder = await reviewOrder(this.activeOrderId, {
					rating: this.rating,
					review: this.review
				})
				const targetIndex = this.orders.findIndex(item => item.id === this.activeOrderId)
				if (targetIndex !== -1) {
					this.orders.splice(targetIndex, 1, updatedOrder)
				}
				this.submitted = true
				setTimeout(() => {
					this.closeRating()
				}, 1000)
			} catch (error) {
				uni.showToast({
					title: error.message || '提交评价失败',
					icon: 'none'
				})
			}
		}
	}
}
</script>

<style scoped>
.page { min-height: 100vh; padding-bottom: 110px; background: #FAFAF8; }
.header { padding: 30px 20px 10px; display: flex; flex-direction: column; }
.title { font-size: 24px; font-weight: 800; color: #2D2D2D; }
.sub { margin-top: 6px; font-size: 18px; color: #9CA3AF; }
.refresh-tip { margin-top: 4px; font-size: 14px; color: #9CA3AF; }
.current-card { margin: 0 20px; padding: 16px; border-radius: 16px; background: #FFFFFF; box-shadow: 0 2px 12px rgba(45,45,45,.06); }
.current-label { font-size: 14px; color: #9CA3AF; }
.current-name { display: block; margin-top: 6px; font-size: 20px; font-weight: 800; color: #2D2D2D; }
.current-desc { display: block; margin-top: 6px; font-size: 14px; line-height: 1.55; color: #6B7280; }
.tabs { padding: 12px 20px; display: flex; gap: 12px; }
.tab { height: 44px; min-width: 80px; padding: 0 18px; border-radius: 22px; background: #F3F0EB; display: flex; align-items: center; justify-content: center; gap: 6px; color: #6B7280; font-size: 18px; font-weight: 800; }
.tab.active { background: #2B9A6F; color: #FFFFFF; box-shadow: 0 4px 12px rgba(43,154,111,.25); }
.count { padding: 2px 6px; border-radius: 999px; background: rgba(255,255,255,.24); font-size: 14px; }
.list { padding: 0 20px; }
.empty { padding: 64px 0; display: flex; flex-direction: column; align-items: center; gap: 12px; color: #9CA3AF; font-size: 18px; }
.order-card { margin-bottom: 16px; padding: 20px; border-radius: 20px; background: #FFFFFF; box-shadow: 0 2px 12px rgba(45,45,45,.06), 0 1px 4px rgba(45,45,45,.04); }
.row, .info-line, .companion, .score, .small-stars { display: flex; align-items: center; }
.between { justify-content: space-between; }
.order-id { font-size: 16px; color: #9CA3AF; }
.badge { padding: 5px 12px; border-radius: 20px; font-size: 15px; font-weight: 700; }
.patient-banner { margin-top: 14px; padding: 10px 12px; border-radius: 12px; background: #F3F0EB; }
.patient-banner.current { background: #E8F5EE; }
.patient-text { font-size: 15px; font-weight: 700; color: #2D2D2D; }
.service-name { display: block; margin-top: 14px; font-size: 18px; font-weight: 800; color: #2D2D2D; }
.info-line { margin-top: 8px; gap: 6px; font-size: 18px; color: #6B7280; }
.progress-box { margin-top: 12px; padding: 12px; border-radius: 14px; background: #F7FAF8; }
.progress-title { display: block; font-size: 16px; font-weight: 800; color: #2B9A6F; }
.progress-proof { display: block; margin-top: 4px; font-size: 14px; color: #6B7280; }
.companion { margin-top: 14px; padding: 12px; border-radius: 14px; background: #F3F0EB; gap: 12px; }
.avatar { width: 40px; height: 40px; border-radius: 50%; background: linear-gradient(135deg, #E8F5EE 0%, #D4EDE2 100%); color: #2B9A6F; font-weight: 800; display: flex; align-items: center; justify-content: center; }
.companion-main { flex: 1; display: flex; flex-direction: column; min-width: 0; }
.companion-name { font-size: 18px; font-weight: 800; color: #2D2D2D; }
.companion-stage { margin-top: 3px; font-size: 14px; color: #6B7280; }
.score { gap: 3px; font-size: 16px; font-weight: 700; color: #2D2D2D; }
.review-box { margin-top: 12px; padding: 12px; border-radius: 14px; background: #FFF9F0; font-size: 16px; line-height: 1.5; color: #6B7280; }
.small-stars { gap: 2px; margin-bottom: 6px; }
.footer { padding-top: 12px; }
.total-label { font-size: 16px; color: #9CA3AF; }
.total { font-size: 22px; font-weight: 800; color: #2B9A6F; }
.primary, .outline { height: 44px; padding: 0 18px; border-radius: 14px; display: flex; align-items: center; justify-content: center; gap: 4px; font-size: 18px; font-weight: 800; }
.primary { background: linear-gradient(135deg, #2B9A6F 0%, #3DB88A 100%); color: #FFFFFF; }
.outline { border: 1px solid #2B9A6F; color: #2B9A6F; }
.sheet-mask { position: fixed; inset: 0; z-index: 80; background: rgba(0,0,0,.35); display: flex; align-items: flex-end; }
.sheet { width: 100%; padding: 12px 24px calc(40px + env(safe-area-inset-bottom)); border-radius: 28px 28px 0 0; background: #FFFFFF; }
.sheet-handle { width: 40px; height: 4px; margin: 0 auto 18px; border-radius: 999px; background: #E8E5E0; }
.sheet-title { display: block; text-align: center; font-size: 20px; font-weight: 800; color: #2D2D2D; }
.rating-row { margin: 24px 0; display: flex; justify-content: center; gap: 12px; }
.textarea { width: 100%; min-height: 120px; padding: 16px; border-radius: 16px; background: #F3F0EB; font-size: 16px; color: #2D2D2D; }
.submit { margin-top: 18px; height: 56px; border-radius: 16px; background: linear-gradient(135deg, #2B9A6F 0%, #3DB88A 100%); display: flex; align-items: center; justify-content: center; color: #FFFFFF; font-size: 18px; font-weight: 800; }
.submit.disabled { background: #E8E5E0; }
.thanks { padding: 36px 0; display: flex; flex-direction: column; align-items: center; gap: 14px; font-size: 18px; font-weight: 800; color: #2D2D2D; }
.thanks-icon { width: 64px; height: 64px; border-radius: 50%; background: #E8F5EE; display: flex; align-items: center; justify-content: center; }
</style>
