// user-app/doc/安诊达原型文件/src/pages/Profile.tsx
import { useState } from "react";
import {
  Phone,
  MapPin,
  Heart,
  Type,
  Mic,
  Contrast,
  HelpCircle,
  MessageSquare,
  Info,
  LogOut,
  ChevronRight,
  Camera,
  Award,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { FadeIn, Stagger, fadeUp, motion } from "@/components/MotionPrimitives";

interface SettingItem {
  icon: React.ElementType;
  label: string;
  iconColor: string;
  iconBg: string;
  type: "link" | "switch" | "slider";
  value?: boolean;
}

const serviceSettings: SettingItem[] = [
  {
    icon: Phone,
    label: "紧急联系人",
    iconColor: "#E85D4A",
    iconBg: "#FFF0ED",
    type: "link",
  },
  {
    icon: MapPin,
    label: "常用医院",
    iconColor: "#4A90D9",
    iconBg: "#EBF3FC",
    type: "link",
  },
  {
    icon: Heart,
    label: "服务偏好",
    iconColor: "#E85D4A",
    iconBg: "#FFF0ED",
    type: "link",
  },
];

const accessibilitySettings: SettingItem[] = [
  {
    icon: Type,
    label: "字体大小",
    iconColor: "#2B9A6F",
    iconBg: "#E8F5EE",
    type: "slider",
  },
  {
    icon: Mic,
    label: "语音助手",
    iconColor: "#4A90D9",
    iconBg: "#EBF3FC",
    type: "switch",
    value: true,
  },
  {
    icon: Contrast,
    label: "高对比度模式",
    iconColor: "#2D2D2D",
    iconBg: "#F3F0EB",
    type: "switch",
    value: false,
  },
];

const otherSettings: SettingItem[] = [
  {
    icon: HelpCircle,
    label: "帮助中心",
    iconColor: "#F5A623",
    iconBg: "#FFF5E0",
    type: "link",
  },
  {
    icon: MessageSquare,
    label: "意见反馈",
    iconColor: "#7C6BC4",
    iconBg: "#F3EEFB",
    type: "link",
  },
  {
    icon: Info,
    label: "关于安诊达",
    iconColor: "#2B9A6F",
    iconBg: "#E8F5EE",
    type: "link",
  },
];

const fontSizeLabels = ["小", "标准", "大"];

export default function Profile() {
  const [voiceEnabled, setVoiceEnabled] = useState(true);
  const [highContrast, setHighContrast] = useState(false);
  const [fontSizeIndex, setFontSizeIndex] = useState(2);

  const renderSettingItem = (item: SettingItem, _index: number, isLast: boolean) => {
    return (
      <motion.div key={item.label} variants={fadeUp}>
        <div
          className="flex items-center gap-4 py-4 px-1"
          style={{
            borderBottom: isLast ? "none" : "1px solid #F3F0EB",
            minHeight: "56px",
          }}
        >
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
            style={{ background: item.iconBg }}
          >
            <item.icon className="w-5 h-5" style={{ color: item.iconColor }} />
          </div>
          <span
            className="text-base font-medium grow"
            style={{ color: "#2D2D2D", fontSize: "18px" }}
          >
            {item.label}
          </span>

          {item.type === "link" && (
            <ChevronRight className="w-5 h-5" style={{ color: "#9CA3AF" }} />
          )}

          {item.type === "switch" && item.label === "语音助手" && (
            <Switch
              checked={voiceEnabled}
              onCheckedChange={setVoiceEnabled}
              className="scale-125"
            />
          )}

          {item.type === "switch" && item.label === "高对比度模式" && (
            <Switch
              checked={highContrast}
              onCheckedChange={setHighContrast}
              className="scale-125"
            />
          )}

          {item.type === "slider" && (
            <div className="flex items-center gap-3">
              {fontSizeLabels.map((label, i) => (
                <button
                  key={label}
                  onClick={() => setFontSizeIndex(i)}
                  className="px-3 py-1.5 rounded-lg font-medium transition-all"
                  style={{
                    background: fontSizeIndex === i ? "#2B9A6F" : "#F3F0EB",
                    color: fontSizeIndex === i ? "#FFFFFF" : "#6B7280",
                    fontSize: i === 0 ? "14px" : i === 1 ? "16px" : "18px",
                  }}
                >
                  {label}
                </button>
              ))}
            </div>
          )}
        </div>
      </motion.div>
    );
  };

  const renderSection = (
    title: string,
    items: SettingItem[]
  ) => (
    <Card
      className="border-0 overflow-hidden"
      style={{
        borderRadius: "16px",
        boxShadow: "0 2px 12px rgba(45,45,45,0.06)",
      }}
    >
      <div className="px-5 pt-4 pb-1">
        <p
          className="text-base font-medium mb-1"
          style={{ color: "#9CA3AF" }}
        >
          {title}
        </p>
      </div>
      <Stagger className="px-4">
        {items.map((item, index) =>
          renderSettingItem(item, index, index === items.length - 1)
        )}
      </Stagger>
    </Card>
  );

  return (
    <div className="min-h-screen pb-24" style={{ background: "#FAFAF8" }}>
      {/* Profile Hero */}
      <div
        className="px-5 pt-10 pb-8"
        style={{
          background: "linear-gradient(180deg, #E8F5EE 0%, #FAFAF8 100%)",
        }}
      >
        <FadeIn>
          <div className="flex flex-col items-center text-center">
            <div className="relative mb-4">
              <div
                className="w-20 h-20 rounded-full flex items-center justify-center text-white text-3xl font-bold"
                style={{
                  background: "linear-gradient(135deg, #2B9A6F, #3DB88A)",
                  boxShadow: "0 4px 16px rgba(43,154,111,0.3)",
                }}
              >
                张
              </div>
              <button
                className="absolute bottom-0 right-0 w-7 h-7 rounded-full flex items-center justify-center"
                style={{
                  background: "#FFFFFF",
                  boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
                }}
              >
                <Camera className="w-3.5 h-3.5" style={{ color: "#6B7280" }} />
              </button>
            </div>

            <h1
              className="text-2xl font-bold mb-1"
              style={{ color: "#2D2D2D" }}
            >
              张奶奶
            </h1>
            <p className="text-base mb-3" style={{ color: "#6B7280" }}>
              138****5678
            </p>
            <div
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-full"
              style={{ background: "#FFF5E0" }}
            >
              <Award className="w-4 h-4" style={{ color: "#F5A623" }} />
              <span
                className="text-base font-medium"
                style={{ color: "#F5A623" }}
              >
                金牌会员
              </span>
            </div>
          </div>
        </FadeIn>
      </div>

      {/* Stats Row */}
      <FadeIn delay={0.1}>
        <div className="px-5 -mt-2 mb-5">
          <Card
            className="border-0 p-4"
            style={{
              borderRadius: "16px",
              boxShadow: "0 2px 12px rgba(45,45,45,0.06)",
            }}
          >
            <div className="grid grid-cols-3 divide-x" style={{ borderColor: "#F3F0EB" }}>
              <div className="text-center px-2">
                <p
                  className="text-xl font-bold"
                  style={{ color: "#2B9A6F" }}
                >
                  12
                </p>
                <p className="text-base" style={{ color: "#6B7280" }}>
                  服务次数
                </p>
              </div>
              <div className="text-center px-2">
                <p
                  className="text-xl font-bold"
                  style={{ color: "#4A90D9" }}
                >
                  3
                </p>
                <p className="text-base" style={{ color: "#6B7280" }}>
                  绑定家人
                </p>
              </div>
              <div className="text-center px-2">
                <p
                  className="text-xl font-bold"
                  style={{ color: "#F5A623" }}
                >
                  680
                </p>
                <p className="text-base" style={{ color: "#6B7280" }}>
                  积分
                </p>
              </div>
            </div>
          </Card>
        </div>
      </FadeIn>

      {/* Settings Sections */}
      <div className="px-5 space-y-4">
        <FadeIn delay={0.15}>
          {renderSection("服务设置", serviceSettings)}
        </FadeIn>

        <FadeIn delay={0.2}>
          {renderSection("辅助功能", accessibilitySettings)}
        </FadeIn>

        <FadeIn delay={0.25}>
          {renderSection("其他", otherSettings)}
        </FadeIn>

        {/* Logout Button */}
        <FadeIn delay={0.3}>
          <Button
            variant="outline"
            className="w-full h-14 text-base font-medium rounded-xl mt-4"
            style={{
              borderColor: "#E85D4A",
              color: "#E85D4A",
              background: "transparent",
            }}
          >
            <LogOut className="w-5 h-5 mr-2" />
            退出登录
          </Button>
        </FadeIn>
      </div>
    </div>
  );
}

// user-app/pages/profile/index.vue
<template>
	<AzShell active="profile">
		<view class="page">
			<view class="hero">
				<view class="avatar-wrap">
					<view class="avatar">{{ displayName.charAt(0) }}</view>
					<view class="camera">
						<AzIcon name="camera" :size="14" color="#6B7280" />
					</view>
				</view>
				<text class="name">{{ displayName }}</text>
				<text class="phone">138****5678</text>
				<view class="member">
					<AzIcon name="award" :size="16" color="#F5A623" />
					<text>金牌会员</text>
				</view>
			</view>

			<view class="stats">
				<view class="stat">
					<text class="num green">{{ familyState.patients.length }}</text>
					<text>就诊人</text>
				</view>
				<view class="stat border">
					<text class="num blue">{{ familyState.familyBindings.length }}</text>
					<text>已绑定家人</text>
				</view>
				<view class="stat border">
					<text class="num gold">{{ pendingTaskCount }}</text>
					<text>家庭代办</text>
				</view>
			</view>

			<view class="sections">
				<view class="card">
					<text class="card-title">辅助功能</text>

					<view class="setting last">
						<view class="item-icon" style="background: #E8F5EE;">
							<AzIcon name="type" :size="20" color="#2B9A6F" />
						</view>
						<view class="setting-main">
							<text class="setting-label">界面大小</text>
							<text class="setting-desc">{{ currentSizeDesc }}</text>
						</view>
						<view class="font-row">
							<text
								v-for="option in fontSizeOptions"
								:key="option.value"
								class="font-chip"
								:class="{ active: settings.fontSizeLevel === option.value }"
								@tap.stop="changeFontSize(option.value)"
							>
								{{ option.label }}
							</text>
						</view>
					</view>

					<view class="setting">
						<view class="item-icon" style="background: #EBF3FC;">
							<AzIcon name="mic" :size="20" color="#4A90D9" />
						</view>
						<view class="setting-main">
							<text class="setting-label">语音助手</text>
							<text class="setting-desc">{{ settings.voiceAssistantEnabled ? '已开启，页面会显示语音助手按钮' : '已关闭，页面会隐藏语音助手按钮' }}</text>
						</view>
						<view class="switch" :class="{ on: settings.voiceAssistantEnabled }" @tap.stop="toggleVoiceAssistant">
							<view />
						</view>
					</view>

					<view class="setting last" @tap="handleOtherItem(helpCenterItem)">
						<view class="item-icon" :style="{ background: helpCenterItem.bg }">
							<AzIcon :name="helpCenterItem.icon" :size="20" :color="helpCenterItem.color" />
						</view>
						<view class="setting-main">
							<text class="setting-label">{{ helpCenterItem.label }}</text>
							<text class="setting-desc">{{ helpCenterItem.desc }}</text>
						</view>
						<AzIcon name="right" :size="22" color="#9CA3AF" />
					</view>
				</view>

				<view class="card">
					<text class="card-title">服务设置</text>
					<view
						v-for="(item, index) in serviceItems"
						:key="item.label"
						class="setting"
						:class="{ last: index === serviceItems.length - 1 }"
						@tap="goServicePage(item)"
					>
						<view class="item-icon" :style="{ background: item.bg }">
							<AzIcon :name="item.icon" :size="20" :color="item.color" />
						</view>
						<view class="setting-main">
							<text class="setting-label">{{ item.label }}</text>
							<text class="setting-desc">{{ item.desc }}</text>
						</view>
						<AzIcon name="right" :size="22" color="#9CA3AF" />
					</view>
				</view>

				<view class="card">
					<text class="card-title">其他</text>
					<view
						v-for="(item, index) in otherItems"
						:key="item.label"
						class="setting"
						:class="{ last: index === otherItems.length - 1 }"
						@tap="handleOtherItem(item)"
					>
						<view class="item-icon" :style="{ background: item.bg }">
							<AzIcon :name="item.icon" :size="20" :color="item.color" />
						</view>
						<text class="setting-label">{{ item.label }}</text>
						<AzIcon name="right" :size="22" color="#9CA3AF" />
					</view>
				</view>

				<view class="logout" @tap="showSoon('退出登录')">
					<AzIcon name="logout" :size="20" color="#E85D4A" />
					退出登录
				</view>
			</view>
		</view>
	</AzShell>
</template>

<script>
import AzShell from '@/components/AzShell.vue'
import AzIcon from '@/components/AzIcon.vue'
import {
	accessibilityState,
	getFontSizeOptions,
	initAccessibilitySettings,
	setFontSizeLevel,
	setVoiceAssistantEnabled
} from '@/utils/accessibility.js'
import { familyCareState, getCurrentPatient, initFamilyCareStore } from '@/utils/family-care.js'

export default {
	components: { AzShell, AzIcon },
	data() {
		return {
			fontSizeOptions: getFontSizeOptions(),
			serviceItems: [
				{ icon: 'user', label: '就诊人管理', desc: '管理多个就诊人，快速切换当前服务对象', color: '#E85D4A', bg: '#FFF0ED', url: '/pages/patients/index' },
				{ icon: 'users', label: '家人绑定', desc: '绑定家人后，可协助预约、缴费和查看记录', color: '#4A90D9', bg: '#EBF3FC', url: '/pages/family-binding/index' },
				{ icon: 'heart', label: '家庭代办', desc: '代预约、代缴费、查看记录、绑定新家人', color: '#2B9A6F', bg: '#E8F5EE', url: '/pages/family/index' }
			],
			otherItems: [
				{ icon: 'message', label: '意见反馈', color: '#7C6BC4', bg: '#F3EEFB' },
				{ icon: 'info', label: '关于安诊达', color: '#2B9A6F', bg: '#E8F5EE' }
			]
		}
	},
	computed: {
		settings() {
			return accessibilityState
		},
		familyState() {
			return familyCareState
		},
		currentPatient() {
			return getCurrentPatient()
		},
		displayName() {
			return this.currentPatient?.name || '安诊达用户'
		},
		pendingTaskCount() {
			return this.familyState.familyTaskOrders.filter(item => item.canPay || item.status === '已预约').length
		},
		currentSizeDesc() {
			return this.settings.fontSizeLevel === 'xlarge'
				? '超大：字体、按钮和卡片都会明显放大'
				: '大：当前适合日常使用的界面大小'
		},
		helpCenterItem() {
			return {
				icon: 'help',
				label: '帮助中心',
				desc: '点击查看使用帮助，也可以语音讲解',
				color: '#F5A623',
				bg: '#FFF5E0',
				url: '/pages/help/index'
			}
		}
	},
	created() {
		initAccessibilitySettings()
		initFamilyCareStore()
	},
	methods: {
		changeFontSize(level) {
			setFontSizeLevel(level)
		},
		toggleVoiceAssistant() {
			setVoiceAssistantEnabled(!this.settings.voiceAssistantEnabled)
		},
		goServicePage(item) {
			uni.navigateTo({ url: item.url })
		},
		handleOtherItem(item) {
			if (item.url) {
				uni.navigateTo({ url: item.url })
				return
			}
			this.showSoon(item.label)
		},
		showSoon(label) {
			uni.showToast({
				title: `${label}正在完善中`,
				icon: 'none'
			})
		}
	}
}
</script>

<style scoped>
.page { min-height: 100vh; padding-bottom: 112px; background: #FAFAF8; }
.hero { padding: 44px 20px 34px; background: linear-gradient(180deg, #E8F5EE 0%, #FAFAF8 100%); display: flex; flex-direction: column; align-items: center; text-align: center; }
.avatar-wrap { position: relative; margin-bottom: 14px; }
.avatar { width: 80px; height: 80px; border-radius: 50%; background: linear-gradient(135deg, #2B9A6F, #3DB88A); box-shadow: 0 4px 16px rgba(43,154,111,.3); display: flex; align-items: center; justify-content: center; color: #FFFFFF; font-size: 30px; font-weight: 800; }
.camera { position: absolute; right: 0; bottom: 0; width: 28px; height: 28px; border-radius: 50%; background: #FFFFFF; box-shadow: 0 2px 8px rgba(0,0,0,.1); display: flex; align-items: center; justify-content: center; }
.name { font-size: 24px; font-weight: 800; color: #2D2D2D; }
.phone { margin-top: 6px; font-size: 16px; color: #6B7280; }
.member { margin-top: 12px; padding: 6px 14px; border-radius: 999px; background: #FFF5E0; display: flex; align-items: center; gap: 6px; color: #F5A623; font-size: 16px; font-weight: 700; }
.stats { margin: -10px 20px 20px; padding: 16px; border-radius: 16px; background: #FFFFFF; box-shadow: 0 2px 12px rgba(45,45,45,.06); display: flex; position: relative; z-index: 2; }
.stat { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 4px; color: #6B7280; font-size: 16px; }
.stat.border { border-left: 1px solid #F3F0EB; }
.num { font-size: 22px; font-weight: 800; }
.green { color: #2B9A6F; }
.blue { color: #4A90D9; }
.gold { color: #F5A623; }
.sections { padding: 0 20px; display: flex; flex-direction: column; gap: 16px; }
.card { border-radius: 16px; background: #FFFFFF; box-shadow: 0 2px 12px rgba(45,45,45,.06); overflow: hidden; }
.card-title { display: block; padding: 16px 20px 4px; color: #9CA3AF; font-size: 16px; font-weight: 700; }
.setting { min-height: 68px; margin: 0 16px; padding: 12px 4px; border-bottom: 1px solid #F3F0EB; display: flex; align-items: center; gap: 14px; }
.setting.last { border-bottom: 0; }
.setting-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 4px; }
.item-icon { width: 40px; height: 40px; border-radius: 12px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.setting-label { font-size: 18px; font-weight: 700; color: #2D2D2D; }
.setting-desc { font-size: 14px; line-height: 1.5; color: #9CA3AF; }
.switch { width: 52px; height: 30px; border-radius: 999px; background: #D1D5DB; padding: 3px; display: flex; align-items: center; flex-shrink: 0; }
.switch view { width: 24px; height: 24px; border-radius: 50%; background: #FFFFFF; box-shadow: 0 1px 3px rgba(0,0,0,.2); transition: transform .2s; }
.switch.on { background: #2B9A6F; justify-content: flex-end; }
.font-row { display: flex; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }
.font-chip { min-width: 52px; padding: 8px 10px; border-radius: 8px; background: #F3F0EB; color: #6B7280; font-size: 14px; font-weight: 700; text-align: center; }
.font-chip.active { background: #2B9A6F; color: #FFFFFF; }
.logout { height: 56px; border-radius: 14px; border: 1px solid #E85D4A; display: flex; align-items: center; justify-content: center; gap: 8px; color: #E85D4A; font-size: 16px; font-weight: 800; }
</style>
